const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  
  console.log("Deploying contracts with the account:", deployer.address);
  console.log("Account balance:", (await ethers.provider.getBalance(deployer.address)).toString());

  // Get the ContractFactory (Contract name is VotingSystem)
  const VotingSystem = await ethers.getContractFactory("VotingSystem");
  
  // Deploy the contract
  const voting = await VotingSystem.deploy();
  
  await voting.waitForDeployment();
  
  const contractAddress = await voting.getAddress();
  
  console.log("✅ VotingSystem contract deployed to:", contractAddress);
  
  // Save contract address to a file for frontend to use
  const configPath = path.join(__dirname, "../../frontend/src/contractConfig.js");
  const configContent = `// This file is auto-generated by the deployment script
export const CONTRACT_ADDRESS = "${contractAddress}";
`;
  
  fs.writeFileSync(configPath, configContent);
  console.log("✅ Contract address saved to frontend/src/contractConfig.js");
  
  // Also save to backend for reference
  const backendConfigPath = path.join(__dirname, "../contractAddress.txt");
  fs.writeFileSync(backendConfigPath, contractAddress);
  console.log("✅ Contract address saved to backend/contractAddress.txt");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });